DEBUG = False
SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'
DATABASE_CONNECT_OPTIONS = {}
SECRET_KEY='secret'

MAX_IMAGES=100
ALLOWED_DOMAINS=[]

DEFAULT_SHAPE='square'
CACHE_VERSION=1404745082

BASIC_AUTH=False
USERS={}
